#' Indexing and quantification.
#'
#'
#' A function that computes indexing and quantification using default settings
#' of Salmon. Make sure Salmon has been installed. If not, run
#' `install()` function before calling `quantification()`.
#'
#'
#'@param species A string indicating the specific name of the species to get
#'     reference transcriptome.
#'@param release A string indicating the release version of the reference.
#'     Default is the current release.
#'@param indexNam A string indicating the name of the output index file.
#'@param fastq A character vector indicating the fastq files of sequences.
#'@param quantOut A character vector indicating the names for quantification files.
#'
#'
#'@return Returns quantification files generated by Salmon program saved in
#' quantOut directory.
#'
#'
#' @examples
#' quantification(species = "Caenorhabditis Elegans",
#'               release = NA,
#'               indexName = "celegansINDEX",
#'               fastq = "celegans.fastq",
#'               quantOut = "celegansQUANT")
#'
#'
#' @references
#' Patro, R., Duggal, G., Love, M. et al. Salmon provides fast and bias-aware
#' quantification of transcript expression. Nat Methods 14, 417–419 (2017).
#' \href{https://doi.org/10.1038/nmeth.4197}
#'
#' Ushey K, Allaire J, Wickham H, Ritchie G (2022). rstudioapi: Safely Access
#' the RStudio API.
#' \href{https://rstudio.github.io/rstudioapi/}
#' \href{https://github.com/rstudio/rstudioapi}
#'
#'
#'
#' @export
#' @import rstudioapi
#'
quantification <- function(species = NA,
                           release = NA,
                           indexName = "index",
                           fastq,
                           quantOut){

    # Obtain .cdna.all.fa.gz and .dna.toplevel.fa.gz from Ensembl database
    cdna <- obtainCDNA(species = species, wantedVersion=release, download=T)
    dna <- obtainDNA(species = species, wantedVersion=release, download=T)

    myTerm <- rstudioapi::terminalCreate()
    rstudioapi::terminalSend(myTerm, "conda activate salmon\n")

    # Combine the two gz files to one
    currentDir <- getwd()
    rstudioapi::terminalSend(myTerm, paste0("cd ", currentDir, "\n"))
    rstudioapi::terminalSend(myTerm, paste0("cdna=", cdna, "\n"))

    rstudioapi::terminalSend(myTerm, paste0("dna=", dna, "\n"))

    rstudioapi::terminalSend(myTerm, "cat $cdna $dna > gentrome.fa.gz\n")

    # Build index
    rstudioapi::terminalSend(myTerm, paste0("indexName=", indexName, '\n'))

    rstudioapi::terminalSend(myTerm,
                             "salmon index -t gentrome.fa.gz -i $indexName\n")


    # Quantification
    for (i in seq(length(fastq))){
        rstudioapi::terminalSend(myTerm, paste0("fastq=", fastq[i], "\n"))

        rstudioapi::terminalSend(myTerm, paste0("quantOut=", quantOut[i], "\n"))

        quantCommand <- paste0("salmon quant -i $indexName",
                               " -l A -r $fastq --validateMappings",
                               " -o $quantOut\n")
        rstudioapi::terminalSend(myTerm, quantCommand)
    }
    # # Remove files used for indexing
    # rstudioapi::terminalSend(myTerm, paste("rm", cdna, dna,
    #                                        "gentrome.fa.gz\n", sep = " "))
}


# [END]
